#!/usr/bin/env bash
#### Sonar - A WiFi Keepalive daemon
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2022
#### https://github.com/mainsail-crew/sonar
####
#### This File is distributed under GPLv3
####
# shellcheck disable=all

# sonar repo
[[ -n "$SONAR_REPO_SHIP" ]] || SONAR_REPO_SHIP=https://github.com/mainsail-crew/sonar.git
[[ -n "$SONAR_REPO_BRANCH" ]] || SONAR_REPO_BRANCH="main"

# Other lines no longer needed -Platima 2025-06-03
