#!/usr/bin/env bash
#Shebang for better file detection
#### mainsail module
####
#### Based on work of:
#### Raymond Himle and meteyou (Stefan Dej)
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2021 - 2022
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####
#### Credits: Thanks to Arksine for this great API :)

[ -n "$MOONRAKER_REPO_SHIP" ] || MOONRAKER_REPO_SHIP=https://github.com/Arksine/moonraker.git
# 2025-05-11 Plaitma
# tag 0.8.0 is verified and was releasd when Mainsail 1.3.2 was built
# current fails inexplicably:
# Cloning into 'moonraker'...
# Generating packages file ...
# build failed, unmounting image...
[ -n "$MOONRAKER_REPO_BRANCH" ] || MOONRAKER_REPO_BRANCH="v0.8.0"
#[ -n "$MOONRAKER_REPO_BRANCH" ] || MOONRAKER_REPO_BRANCH=master
