#!/usr/bin/env bash
#### MainsailOS Specific Tweaks for images using resolved that
#### would otherwise have a broken symlink for /etc/resolv.conf
#### during build chroot.
#### 
#### This is called via BASE_POSTSCRIPT, not as a module as that
#### is actually too late.
####
#### Written by Platima <wave@plati.ma>
#### Copyright 2025 - till today
#### https://github.com/platima/MainsailOS
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

if [ -e /etc/resolv.conf.mainsail_bak ]; then
        if [ -e /etc/resolv.conf ]; then rm /etc/resolv.conf; fi
        mv /etc/resolv.conf.mainsail_bak /etc/resolv.conf
        echo_green "Restored original resolv.conf"
fi
