#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

export BASE_ARCH="arm64"

# Image source
export DOWNLOAD_URL_CHECKSUM="https://au.sbcmirror.org/armbian/dl/orangepi5/archive/Armbian_25.2.1_Orangepi5_noble_current_6.12.13.img.xz.sha"
export DOWNLOAD_URL_IMAGE="https://au.sbcmirror.org/armbian/dl/orangepi5/archive/Armbian_25.2.1_Orangepi5_noble_current_6.12.13.img.xz"

export BASE_ROOT_PARTITION="1"
export BASE_IMAGE_ENLARGEROOT=3000
export BASE_BOOT_MOUNT_PATH=boot

export MODULES="resolveconf,base,pkgupgrade,udev_fix,armbian(armbian_net,mainsailos,klipper,is_req_preinstall,moonraker,mainsail,timelapse,crowsnest,sonar)"

export ARMBIAN_CONFIG_ORANGEPI_5B_PATCH=true
export ARMBIAN_CONFIG_ORANGEPI_RESOLVCONF=true

### JSON sniplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_PRETTY_SBC_NAME="Orange Pi 5B"
# shellcheck disable=SC2034
JSON_SUPPORTED_SBC="orangepi5b-64bit"
