#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

export BASE_ARCH="arm64"

# Image source
# Cannot use Noble - too new
# Fails at Moonraker after 28m 57s
export DOWNLOAD_URL_IMAGE="https://au.sbcmirror.org/armbian/dl/rock-3a/archive/Armbian_25.2.1_Rock-3a_bookworm_current_6.12.13_minimal.img.xz"
export DOWNLOAD_URL_CHECKSUM="https://au.sbcmirror.org/armbian/dl/rock-3a/archive/Armbian_25.2.1_Rock-3a_bookworm_current_6.12.13_minimal.img.xz.sha"

# Fix for "mount: /home/owner/actions-runner/_work/MainsailOS/MainsailOS/repository/src/workspace/mount/boot/firmware: mount point does not exist."
export BASE_BOOT_MOUNT_PATH=boot

### JSON sniplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_PRETTY_SBC_NAME="Radxa Rock 3A"
# shellcheck disable=SC2034
JSON_SUPPORTED_SBC="radxarock3a-64bit"
