#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

BASE_ARCH="arm64"

# Image source
DOWNLOAD_URL_CHECKSUM="https://github.com/platima/sbc-images/raw/refs/heads/main/Radxa/Rock%204%20SE/bookworm%20current%20cli/Armbian-unofficial_24.11.0-trunk_Rock-4se_bookworm_current_6.6.62.img.xz.sha256"
DOWNLOAD_URL_IMAGE="https://github.com/platima/sbc-images/raw/refs/heads/main/Radxa/Rock%204%20SE/bookworm%20current%20cli/Armbian-unofficial_24.11.0-trunk_Rock-4se_bookworm_current_6.6.62.img.xz"

# export Variables
export BASE_ARCH
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE

### JSON sniplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_PRETTY_SBC_NAME="Radxa Rock 4 SE"
# shellcheck disable=SC2034
JSON_SUPPORTED_SBC="radxarock4se-64bit"
