#!/usr/bin/env bash
#### MainsailOS Specific Tweaks for orangepi images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

if [ -e /etc/resolv.conf.mainsail_bak ]; then
        if [ -e /etc/resolv.conf ]; then rm /etc/resolv.conf; fi
        mv /etc/resolv.conf.mainsail_bak /etc/resolv.conf
        echo_green "Restored original resolv.conf"
fi
