#!/usr/bin/env bash
#### MainsailOS Specific Tweaks for orangepi images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

#### NOTE: udev rules file is applied in Step 6!
#### This is based on https://github.com/Arksine/moonraker/issues/562


# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

## Uncomment for deeper debugging
# set -x

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

if [ -L /etc/resolv.conf ] && [ ! -e /etc/resolv.conf ]; then
    echo_green "Found broken symlink at /etc/resolv.conf"
    mv /etc/resolv.conf /etc/resolv.conf.mainsail_bak
    echo "nameserver 1.1.1.1" > /etc/resolv.conf
    echo "nameserver 8.8.8.8" >> /etc/resolv.conf
    echo_green "Added new resolv.conf for build"
fi
