#!/usr/bin/env bash
#### MainsailOS Specific Tweaks for images using resolved that
#### would otherwise have a broken symlink for /etc/resolv.conf
#### during build chroot.
####
#### This is called via BASE_PRESCRIPT, not as a module as that
#### is actually too late.
####
#### Written by Platima <wave@plati.ma>
#### Copyright 2025 - till today
#### https://github.com/platima/MainsailOS
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

## Uncomment for deeper debugging
# set -x

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

if [ -L /etc/resolv.conf ] && [ ! -e /etc/resolv.conf ]; then
    echo_green "Found broken symlink at /etc/resolv.conf"
    mv /etc/resolv.conf /etc/resolv.conf.mainsail_bak
    echo "nameserver 1.1.1.1" > /etc/resolv.conf
    echo "nameserver 8.8.8.8" >> /etc/resolv.conf
    echo_green "Added new resolv.conf for build"
fi

echo_green "/"
ls -Alh /
echo_green "/tmp"
ls -Alh /tmp
echo_green "echo 1 > /tmp/blah"
echo 1 > /tmp/blah
echo_green "cat /tmp/blah"
cat /tmp/blah
exit 1
